name: Update RSS Feeds

on:
  schedule:
    - cron: '0 19 * * *'  # 毎日4:00 JST (19:00 UTC)
  workflow_dispatch:  # 手動実行も可能
  issues:
    types: [opened, labeled]  # 新しいIssueまたはラベル付きIssueの処理

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

jobs:
  process-feed-requests:
    if: github.event_name == 'issues' && (contains(github.event.issue.labels.*.name, 'feed-request') || contains(github.event.issue.title, '新しいフィード作成リクエスト'))
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Process feed request
      run: |
        node -e "
        import('./src/issue-processor.js').then(module => {
          const processor = new module.IssueProcessor();
          const issueData = {
            title: '${{ github.event.issue.title }}',
            body: \`${{ github.event.issue.body }}\`,
            number: ${{ github.event.issue.number }},
            labels: ${{ toJson(github.event.issue.labels) }}
          };
          return processor.processIssue(issueData);
        }).then(result => {
          console.log('Feed request processed:', result);
        }).catch(error => {
          console.error('Error processing feed request:', error);
          process.exit(1);
        });
        "
      
    - name: Generate all feeds
      run: npm run build
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/feeds/ data/feeds/ docs/feeds/index.json
        git diff --staged --quiet || git commit -m "Add new feed from issue #${{ github.event.issue.number }} - $(date -u)"
        git push
    
    - name: Close processed issue
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'フィードが正常に作成されました！以下のURLでアクセスできます：\n\nhttps://${{ github.repository_owner }}.github.io/opendb-feed/feeds/[フィードID].xml\n\n詳細は https://${{ github.repository_owner }}.github.io/opendb-feed/ で確認してください。'
          });
          
          github.rest.issues.update({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed'
          });

  update-all-feeds:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Update all RSS feeds
      run: npm run build
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/feeds/ data/
        git diff --staged --quiet || git commit -m "Update all RSS feeds - $(date -u)"
        git push
      
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4